""" Constants file for Auth0's seed project
"""
ACCESS_TOKEN_KEY = 'access_token'
API_ID = 'API_ID'
APP_JSON_KEY = 'application/json'
AUTH0_CLIENT_ID = 'weRqWlG4Y2ARw0xTMMCknDdCb5R5OIwm'
AUTH0_CLIENT_SECRET = 'Vd4rHmLOHPDGHUeA7W1B72Q4oCBajFlvzeR6t-xNlkkg_oDJqbnXsrXwPxfl3pAW'
AUTH0_CALLBACK_URL = 'https://i.dis.gg/callback'
AUTH0_DOMAIN = 'disgg.auth0.com'
AUTH0_AUDIENCE = ''
AUTHORIZATION_CODE_KEY = 'authorization_code'
CLIENT_ID_KEY = 'client_id'
CLIENT_SECRET_KEY = 'client_secret'
CODE_KEY = 'code'
CONTENT_TYPE_KEY = 'content-type'
GRANT_TYPE_KEY = 'grant_type'
PROFILE_KEY = 'profile'
REDIRECT_URI_KEY = 'redirect_uri'
SECRET_KEY = 'ThisIsTheSecretKey'
JWT_PAYLOAD = 'jwt_payload'
